import {rcaEvents} from "./rcaStore.js";
import * as NotificationService from "../infrastructure/notifications/NotificationService.js";

export async function sendWeeklyRCAReport(){

 if(!rcaEvents.length) return;

 const weekAgo=Date.now()-7*24*60*60*1000;

 const weekly=rcaEvents.filter(
  e=>new Date(e.time).getTime()>weekAgo
 );

 if(!weekly.length) return;

 const counts={};

 weekly.forEach(e=>{
   counts[e.cause]=(counts[e.cause]||0)+1;
 });

 const top=Object.entries(counts)
  .sort((a,b)=>b[1]-a[1])[0];

 const avgHealth=(
   weekly.reduce((a,b)=>a+b.health,0)/weekly.length
 ).toFixed(1);

 const body=`
Weekly RCA Summary Report

Total Anomalies:
${weekly.length}

Most Frequent Root Cause:
${top[0]} (${top[1]} occurrences)

Average System Health:
${avgHealth} %

Recommended Investigation:
Review recurring anomalies related to ${top[0]}

Generated by ML Observability Engine
`;

 await NotificationService.notify({
   eventType:"weekly.rca.summary",
   severity:"INFO",
   category:"APPLICATION",
   source:"nodejs-observability",
   subject:"Weekly RCA Observability Report",
   body
 });

}